### ISSUE TITLE
Cant get quickstart sample to work

### ISSUE THREAD

**Issue by sptjohn** [beyond-code-github/AzureNetQ#4]
Hi

I'm, trying to get the quickstart sample to work against my message queue hosted on Azure. But I get this exception:

![capture](https://cloud.githubusercontent.com/assets/3286687/4387590/f9f04572-43de-11e4-995e-b56ffd6a4926.PNG)

I managed to get it working when using the standard Azure API (following the code in this article: https://www.simple-talk.com/cloud/cloud-data/an-introduction-to-windows-azure-service-bus-brokered-messaging/).

Any ideas?

**Comment by beyond-code-github** [comment]
It may sound like a silly question but is your connection string definitely well formed and the same as in your standard azure example? 

That error is bubbling up from the underlying API on which AzureNetQ is built which should be compatible with the Azure one, so it could well be something straightforward! You could also try connecting using Service Bus Explorer to see if there are any greater issues.

**Comment by sptjohn** [comment]
Hi Pete

Yes, it is exactly the same connection string.

One thing I noticed is that AzureNetQ references the NuGet package ServiceBus.v1_1, whereas the "standard azure example" uses the package "WindowsAzure.ServiceBus".

When I tried to run the "standard Azure example" with ServiceBus.v1_1 instead of WindowsAzure.ServiceBus I got a different exception, saying the old ServiceBus.v1_1 package doesn't support partitioned queues. Don't know if that may be related to this.

**Comment by beyond-code-github** [comment]
Ahhh interesting... if you are trying to work with existing queues that have been created by the azure driver 2.3 or 2.4 then this may cause you issues as the Service Bus 1.1 dll is not compatible with all the very latest features.

Having said that, if you are on a fresh namespace then this shouldn't be causing any issues. If you are really stuck then you can always recompile AzureNetQ from the source and swap out the 1.1 dll for the standard Azure one. Sorry if this isn't much help, but without being able to reproduce it is a little tricky!

**Comment by sptjohn** [comment]
It's a fresh queue created just now (following the steps from the article I mentioned above).

I'll try to fiddle a bit with your code and see if I can switch to the new WindowsAzure.ServiceBus package.

I'll keep you posted if I get it working.

Thx

**Comment by sptjohn** [comment]
I replaced Service Bus 1.1 with WindowsAzure.ServiceBus in AzureNetQ and tried again, but still no success. Really weird!

**Comment by beyond-code-github** [comment]
Indeed, perhaps try removing the queue that was created earlier and see if that makes any difference?
